### ISSUE TITLE
Project is missing a license

### ISSUE THREAD

**Issue by ivanskodje** [Dan6erbond/share-me#1]
I noticed that this repository is missing a license. Having a license is essential to provide clarity on how others can use and distribute the code. 

If there's no license, people can't legally use or share the code. This means they might get in trouble for copyright issues and have to pay money or go to court. Also, it's hard to know what's allowed and what's not when using or sharing the code, since there are no clear rules or guidelines.

Would it be possible to add a license to this repository, such as the MIT License or the GNU General Public License?

**Comment by Dan6erbond** [comment]
Closed in d113622f1.

**Comment by Dan6erbond** [comment]
Closed in d113622f1042fd35cdf1bc6c3dee7fbd0e4875aa.
