### ISSUE TITLE
docs: ShareX Setup

### ISSUE THREAD

**Issue by Ynd21** [Dan6erbond/share-me#37]
```json
{
  "Version": "15.0.0",
  "Name": "Share Me",
  "DestinationType": "ImageUploader",
  "RequestMethod": "POST",
  "RequestURL": "https://Share-Me-Domain.com/api/posts",
  "Headers": {
    "Accept": "*/*",
    "Authorization": "YourTokenHere"
  },
  "Body": "MultipartFormData",
  "FileFormName": "files",
  "URL": "https://Share-Me-Domain.com/posts/{json:id}"
}
```
![ShareX_rnuP7vwkjU](https://github.com/Dan6erbond/share-me/assets/13704380/97f080e3-ed6a-4aee-b7bf-a2c952b31697)

How to add 

1. Right click system tray icon
2. Destinations 
3. Custom Uploader Settings 
4. (1) Import 
5. Paste from Clipboard
6. (2) Ensure Method is POST 
7. (3) Change Domain in Request URL
8. (4) Add API Token received from Share-Me
9. (5) Update Domain URL with Share-Me Domain (can be made a variable if PostURL is an api response field 👀, one less thing to change)
10. (6) Change Image Uploader to Share-Me
11. Close window

**Comment by Dan6erbond** [comment]
Thanks so much! I am currently working on the documentation page with Next.js on [32-docs-add-docusaurus-project-with-installation-configuration-and-usage-instructions](https://github.com/Dan6erbond/share-me/tree/32-docs-add-docusaurus-project-with-installation-configuration-and-usage-instructions) and will include your instructions for the ShareX integration!
